from selenium import webdriver
from selenium.webdriver.common.by import By
from time import sleep
from selenium.webdriver.support.ui import Select
from selenium.common.exceptions import NoSuchElementException
driver = webdriver.Chrome()
# url = "https://www.google.com"
url = "https://friends.walla.co.il/#/login"
driver.maximize_window()
driver.get(url)
# sr = driver.find_element(By.ID, "APjFqb")
# sr = driver.find_element(By.NAME, "q")
# sr.click()
# sr.send_keys("work with selenium")
# bt = driver.find_element(By.XPATH, '//*[@id="root"]/div/div/header/div[1]/div[1]/div[2]/form/button')
#
# driver.find_element(By.LINK_TEXT, 'כניסה').click()
# sleep(1)
# driver.find_element(By.XPATH, '//*[@id="yDmH0d"]/c-wiz/main/div[3]/div/div[2]/div/div/div[1]/div/button/span').click()
# sleep(1)
# driver.find_element(By.XPATH, '//*[@id="yDmH0d"]/c-wiz/main/div[3]/div/div[2]/div/div/div[2]/div/ul/li[1]/span[3]').click()
# sleep(1)
# fname = driver.find_element(By.NAME, 'firstName')
# fname.click()
# fname.send_keys("Alexander")
# driver.find_element(By.XPATH, '//*[@id="collectNameNext"]/div/button/span').click()
# sleep(1)
# day = driver.find_element(By.ID, "day")
# day.click()
# day.send_keys("30")

driver.find_element(By.XPATH, '//*[@id="wrapper"]/section/fieldset/a').click()
user = driver.find_element(By.ID, 'username')
user.click()
user.send_keys("testtest71")
sleep(1)
password = driver.find_element(By.XPATH, '/html/body/app-root/div/div/div[1]/main/div[1]/app-register/form/fieldset/section/ul/li[2]/app-input-password/form/div[1]/input')
password.click()
password.send_keys("QWzx23$%")
sleep(1)
fname = driver.find_element(By.ID, 'fname')
fname.click()
fname.send_keys("Alexander")
sleep(1)
phone = driver.find_element(By.ID, 'postfix')
phone.click()
phone.send_keys("0545773947")
sleep(1)
day = Select(driver.find_element(By.XPATH, '/html/body/app-root/div/div/div[1]/main/div[1]/app-register/form/fieldset/section/ul/li[6]/app-date-picker/form/div[3]/select'))
day.select_by_value('30')
sleep(1)
month = Select(driver.find_element(By.XPATH, '/html/body/app-root/div/div/div[1]/main/div[1]/app-register/form/fieldset/section/ul/li[6]/app-date-picker/form/div[2]/select'))
month.select_by_value('11')
sleep(1)
year = Select(driver.find_element(By.XPATH, '/html/body/app-root/div/div/div[1]/main/div[1]/app-register/form/fieldset/section/ul/li[6]/app-date-picker/form/div[1]/select'))
year.select_by_value('1971')
driver.find_element(By.XPATH, '/html/body/app-root/div/div/div[1]/main/div[1]/app-register/form/fieldset/section/ul/li[7]/app-input-genders/form/fieldset/ul/li[1]/label/span').click()
sleep(1)
driver.find_element(By.XPATH, '/html/body/app-root/div/div/div[1]/main/div[1]/app-register/form/fieldset/section/ul/li[8]/label/span').click()
sleep(1)
driver.find_element(By.ID, 'submit-button').click()
sleep(5)
try:
    check = driver.find_element(By.ID, 'errorPhoneInvalid')
    print("The test passed, because we get alert of invalid phone number")
except NoSuchElementException as err:
    print(err)
driver.close()
